version: '3.5'
services:

  prometheus:
    build:
      context: ./monitoring/prometheus
      dockerfile: Dockerfile
    image: nefariusmag/prometheus:1.0.0
    restart: always
    ports:
      - 9090:9090
    networks:
      - monitoring

  postgres-exporter:
    env_file: .env
    image: wrouesnel/postgres_exporter:v0.4.6
    restart: always
    environment:
      DATA_SOURCE_NAME: 'postgresql://postgres:postgres@${HOST_PROD}:5432/?sslmode=disable'
    ports:
      - 9187:9187
    networks:
      - monitoring

  alertmanager:
    build:
      context: ./monitoring/alertmanager
      dockerfile: Dockerfile
    image: nefariusmag/alertmanager:1.0.0
    depends_on:
      - prometheus
    restart: always
    ports:
      - 9093:9093
    networks:
      - monitoring

  prometheus_bot:
    image: b3vis/prometheus_bot
    depends_on:
      - prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus_bot:/config
    ports:
      - 9087:9087
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:5.0.0-beta4
    depends_on:
      - prometheus
    volumes:
      - ./monitoring/grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - 3000:3000
    networks:
      - monitoring

networks:
  monitoring:
